//PARAMETROS ADICIONAIS NO N1 IMPEDEM DE CASO NAO POR UM DOS PARAMETROS RETORNAR O VALOR
function soma (n1=0,n2=0) {
    return n1 + n2
}

//EXEMPLO DE APENAS UM PARAMETRO INFORMADO
console.log(soma(2))